import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Generated by nextjs tutorial",
    template:"%s | JA"
  },
  description: "Generated by nextjs tutorial",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-sky-400">HEADER</header>
        {children}
        <footer className="bg-lime-500">FOOTER</footer>
      </body>
    </html>
  )
}
